# Generated by Django 5.2 on 2025-05-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
