# Generated by Django 5.2 on 2025-05-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
