# Generated by Django 5.2 on 2025-05-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='fav',
            new_name='is_starred',
        ),
    ]
